version: '3.8'

services:
  mysql:
    image: mysql:8.0.37
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: airvon
    ports:
      - 3307:3306

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
